#
# SPDX-License-Identifier: Apache-2.0
#

version: "2.1"

networks:
  carbonAccounting:

services:
  chaincode-utilityemissions1:
    container_name: chaincode-utilityemissions1.carbonAccounting.com
    image: krybalko/utilityemissions-chaincode:0.0.3
    environment:
      - CHAINCODE_CCID=utilityemissions:c7c3d0c4416ec4fe42f97254e171bf8e0d9c9730f07a091c2f0251e80f12fc02
      - CHAINCODE_ADDRESS=0.0.0.0:9998
    ports:
      - "9998:9998"
