# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2.1'

networks:
  carbonAccounting:

services:

  ca_auditor1:
    image: hyperledger/fabric-ca:1.4.9
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-auditor1
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../organizations/fabric-ca/auditor1:/etc/hyperledger/fabric-ca-server
    container_name: ca_auditor1
    networks:
      - carbonAccounting

  ca_auditor2:
    image: hyperledger/fabric-ca:1.4.9
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-auditor2
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=8054
    ports:
      - "8054:8054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../organizations/fabric-ca/auditor2:/etc/hyperledger/fabric-ca-server
    container_name: ca_auditor2
    networks:
      - carbonAccounting

  ca_auditor3:
    image: hyperledger/fabric-ca:1.4.9
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-auditor3
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=9054
    ports:
      - "9054:9054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../organizations/fabric-ca/auditor3:/etc/hyperledger/fabric-ca-server
    container_name: ca_auditor3
    networks:
      - carbonAccounting

  